### ISSUE TITLE
OS X matplotlib backend fails to run with "Python is not installed as a framework"

### ISSUE THREAD

**Issue by jeremydouglass** [dsmbgu8/image_annotate.py#4]
When first trying to run image_annotate.py on OS X 10.10.5, it fails with a matplotlib error:

```
RuntimeError: Python is not installed as a framework.
```

This seems to be a [widely](http://stackoverflow.com/questions/4130355/python-matplotlib-framework-under-macosx) [reported](http://stackoverflow.com/questions/29433824/unable-to-import-matplotlib-pyplot-as-plt-in-virtualenv) [problem](http://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python), including on [other repos](https://github.com/stevengj/PyCall.jl/issues/218), with two common solutions -- defining the matplotlib backend (e.g. `TkAgg` or `WXAgg`) either in the script or in a system configuration file that will affect all scripts.
1. In the script:
   
   ```
   matplotlib.use('TkAgg')
   ```
2. Or, in a user configuration file:
   
   ```
   echo "backend: TkAgg" >> ~/.matplotlib/matplotlibrc
   ```

Making either change resolved my issue.

---

Error log:

```
Traceback (most recent call last):
  File "./image_annotate.py", line 27, in <module>
    import pylab as pl
  File "/Users/jeremydouglass/.virtualenvs/image_annotate/lib/python2.7/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/Users/jeremydouglass/.virtualenvs/image_annotate/lib/python2.7/site-packages/matplotlib/pylab.py", line 274, in <module>
    from matplotlib.pyplot import *
  File "/Users/jeremydouglass/.virtualenvs/image_annotate/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/jeremydouglass/.virtualenvs/image_annotate/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/jeremydouglass/.virtualenvs/image_annotate/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

**Comment by dsmbgu8** [comment]
Thanks for catching this. I never observed this behavior since my default backend was Qt4Agg. Changing the mpl backend to anything other than MacOSX should resolve this issue.

**Comment by VictorZhang2014** [comment]
What I found a solution for this error message https://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python

**Comment by sharafff** [comment]
Thanks
